version: '3.8'

services:
  meshprom_exporter:
    container_name: meshprom
    build: .
    restart: unless-stopped
    volumes:
      - $HOME/docker/meshprom/data.json:/app/data.json
      - $HOME/docker/meshprom/prom_exporter.py:/app/prom_exporter.py  
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
