version: '3.8'

services:
  mmrelaydevicestat:
    build: device
    # image: mate71pl/mmrelaynode:latest
    container_name: node-device-stats
    restart: always
    volumes:
      - mesh:/home/mesh/
  # ports:
    # - "4403:4403"
    networks:
      - mesh
    entrypoint: ["sh", "-c", "meshtasticd -d /home/mesh -h 12345678"] # change Hardware ID 
    logging:
      driver: "json-file"
      options:
        max-size: "20m"

  meshprom_exporter:
    container_name: meshprom
    build: .
    restart: always
    depends_on:
     - mmrelaydevicestat
    volumes:
     - mesh:/home/mesh
     - $HOME/docker/meshprom/prom_exporter.py:/app/prom_exporter.py
    networks:
     - mesh
    ports:
     - "8000:8000"
    command: ["python", "/app/prom_exporter.py"]
    environment:
     - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "20m"

networks:
  mesh:
    driver: bridge

volumes:
  mesh:

